#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Generate the hook table C source from game/hooks.csv, with sizes from functions.csv.

usage: gen_hooks.py HOOKS_CSV FUNCTIONS_CSV OUT_C
"""
from __future__ import annotations

import csv
import sys


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__, file=sys.stderr)
        return 2
    with open(sys.argv[1], newline='') as f:
        rows = sorted(csv.DictReader(f), key=lambda r: int(r['address'], 16))
    with open(sys.argv[2], newline='') as f:
        sizes = {r['address']: r['size'] for r in csv.DictReader(f)}
    out = ['/* SPDX-License-Identifier: GPL-2.0-or-later */',
           '/* Generated by tools/gen_hooks.py from game/hooks.csv. Do not edit. */',
           '#include "runtime/hooks.h"', '']
    for r in rows:
        out.append(f"void {r['replacement']}(void);")
    out += ['', 'const rt_hook_entry game_hooks[] = {']
    for r in rows:
        out.append(f"    {{ {r['address']}u, {sizes[r['address']]}u, \"{r['replacement']}\", (rt_hook_fn){r['replacement']} }},")
    out += ['    { 0, 0, 0, 0 }', '};', f'const unsigned game_hook_count = {len(rows)}u;', '']
    with open(sys.argv[3], 'w') as f:
        f.write('\n'.join(out))
    return 0


if __name__ == '__main__':
    sys.exit(main())
